### ISSUE TITLE
Git Protocol Version not clear

### ISSUE THREAD

**Issue by vaastav** [google/gitprotocolio#2]
There seems to be both Protocol V1 and V2 files in the codebase. Is the target of the repo to support both protocol versions or just focus on the V2 highlighted in googleblog a few weeks ago? Regardless, better clarity would be nice in the readme.

Additionally what are some of the future tasks? I would love to be a contributor.

**Comment by draftcode** [comment]
I added TODOs in README.

My current focus is to update the upstream protocol spec. To this end, this library was written to check if it can parse and serialize what the canonical Git implementation speaks. This naturally means this library supports V1 and V2.
