### ISSUE TITLE
Project status?

### ISSUE THREAD

**Issue by sluongng** [google/gitprotocolio#3]
Hi,

I am reviewing the implementation here for my personal project and I think there are still some unfinished pieces.

The spec for V2 were also added some new functionality in recent months.

I was wondering if PR are accepted or would you prefer others maintaining a fork? Or perhaps contributing this to https://github.com/go-git/go-git which is still missing a Protocol V2 implementation?

**Comment by sluongng** [comment]
ping @draftcode

**Comment by draftcode** [comment]
If you send a PR, I'll review it. Note that v2 was designed to be more like an RPC protocol so that it can be extended. So this library provides the RPC framing part.
