### ISSUE TITLE
Unable to parse git-upload-pack payload

### ISSUE THREAD

**Issue by sluongng** [google/gitprotocolio#5]
# How to reproduce

```
# Setup server
git clone https://github.com/sluongng/git-cache/
git checkout 07f1136c7d09c8281e4e0d8a8b96e3816dffbdac
go run .

# Setup client
# This should clone git.git from Github through the simple golang proxy
git -c http.extraHeader='GIT-CACHE-UPSTREAM: https://github.com' clone -vvv http://127.0.0.1:8080/git/git.git

```

# Expected result

The middleware layer in https://github.com/sluongng/git-cache/commit/07f1136c7d09c8281e4e0d8a8b96e3816dffbdac#diff-0eb779b9e49d8e44b0f36923fdb8d87d5ee024f886eefc45deec4ec88380a087R56 should be able to parse the request body into ProtocolV2RequestChunk and serialize the Chunks as JSON and log them out.

# Actual result

`ls-ref` command seems to work fine, but the one next `git-upload-pack` command failed to be parse by gitprotocolio

```
Unable to scan request: strconv.ParseUint: parsing "\x1f\x8b\b\x00": invalid syntax
```

Which most likely coming from https://github.com/google/gitprotocolio/blob/b5a56823ae5213a598e042c567d5f0015213150b/token.go#L179

**Comment by sluongng** [comment]
I am using latest Git version compiled from master of https://github.com/git/git/commit/670b81a890

```
~> git version
git version 2.32.0.93.g670b81a890
```

**Comment by draftcode** [comment]
Do you have full pkt-lines on the request? It seems to me that you've read the entire request body, so it should be easy to dump that.

**Comment by sluongng** [comment]
After a bit of tinkering, it seems like the body of the `fetch` command was in gzip and need to be wrapped with a `gzip.NewReader()` before passing to gitprotocolio.

I am closing this issue for now. We can consider adding support for native gzip handling in this lib in a separate discussion (or if it's even needed)

**Comment by sluongng** [comment]
To give future folks some context on how I fixed my issue: https://github.com/sluongng/git-cache/commit/02eca505f9405845a85e53425b50165a008f1a2c
